import asyncio

from temporalio import activity
from github import Auth, Github, GithubException

from app.db.crud import (
    clear_pending_fix_for_repo,
    get_repos_with_pending_pr,
)
from app.db.session import get_session
from app.services import github_service


# ---------------------------------------------------------------------------
# Phase 5: Batch Repo Fetching
# ---------------------------------------------------------------------------

@activity.defn
async def fetch_repo_list_activity(access_token: str, limit: int) -> list[dict]:
    """Fetch the user's repos and return the top N as dicts (0 = all)."""
    repos = await github_service.list_user_repos(access_token)
    if limit > 0:
        repos = repos[:limit]
    return [r.model_dump() for r in repos]


# ---------------------------------------------------------------------------
# Phase 6: Janitor — Pull Request Creation
# ---------------------------------------------------------------------------

def _create_pull_request(repo_full_name: str, content: str, access_token: str) -> str:
    """Create a branch, commit README.md, and open a PR — synchronous PyGithub."""
    g = Github(access_token)
    repo = g.get_repo(repo_full_name)

    # 1. Define a consistent branch name (Idempotent)
    target_branch = "gardener/readme-fix"
    default_branch_name = repo.default_branch
    default_branch = repo.get_branch(default_branch_name)

    # 2. Get or Create the Branch — force-push (reset) if it already exists
    try:
        ref = repo.get_git_ref(f"heads/{target_branch}")
        # Force-update the branch to latest default HEAD so our commit is clean
        ref.edit(sha=default_branch.commit.sha, force=True)
        activity.logger.info("Branch %s reset to %s HEAD (force-push).", target_branch, default_branch_name)
    except GithubException:
        repo.create_git_ref(ref=f"refs/heads/{target_branch}", sha=default_branch.commit.sha)
        activity.logger.info("Created new branch %s", target_branch)

    # 3. Create or Update the README file on that branch
    file_path = "README.md"
    message = "🌿 Gardener: Enhanced Documentation"
    try:
        # Check if file exists ON THE TARGET BRANCH
        contents = repo.get_contents(file_path, ref=target_branch)
        repo.update_file(
            path=file_path,
            message=message,
            content=content,
            sha=contents.sha,
            branch=target_branch,
        )
    except GithubException:
        repo.create_file(
            path=file_path,
            message=message,
            content=content,
            branch=target_branch,
        )

    # 4. Check for an existing Pull Request to avoid duplicates
    existing_prs = repo.get_pulls(
        state="open",
        head=f"{repo.owner.login}:{target_branch}",
        base=default_branch_name,
    )
    if existing_prs.totalCount > 0:
        pr = existing_prs[0]
        activity.logger.info("PR already exists: %s", pr.html_url)
        g.close()
        return pr.html_url

    # 5. Create new PR if none exists
    try:
        pr = repo.create_pull(
            title="🌿 Gardener: Enhanced Documentation",
            body=(
                "This documentation was auto-generated by the GitHub Gardener AI "
                "using deep code analysis with architecture diagrams."
            ),
            head=target_branch,
            base=default_branch_name,
        )
        pr_url = pr.html_url
        g.close()
        return pr_url
    except GithubException as e:
        if e.status == 422 and "No commits between" in str(e.data):
            activity.logger.info("No changes detected between %s and %s. Skipping PR.", target_branch, default_branch_name)
            g.close()
            # Return the branch URL or repo URL so the frontend has something to link to
            return f"{repo.html_url}/tree/{target_branch}"
        raise e


@activity.defn
async def create_pull_request_activity(repo_full_name: str, content: str, access_token: str) -> str:
    """Create a branch with README.md and open a Pull Request."""
    return await asyncio.to_thread(_create_pull_request, repo_full_name, content, access_token)


# ---------------------------------------------------------------------------
# Phase 17: Smart Sync — check PR statuses on GitHub
# ---------------------------------------------------------------------------

def _extract_pr_number(pr_url: str) -> int | None:
    """Extract pull request number from a GitHub PR URL."""
    # Handles URLs like https://github.com/owner/repo/pull/42
    try:
        parts = pr_url.rstrip("/").split("/")
        if "pull" in parts:
            idx = parts.index("pull")
            return int(parts[idx + 1])
    except (ValueError, IndexError):
        pass
    return None


def _sync_pr_status(access_token: str) -> int:
    """Check GitHub for merged/closed PRs and clear pending_fix_url. Returns count updated."""
    with get_session() as session:
        pending = get_repos_with_pending_pr(session)

    if not pending:
        return 0

    g = Github(auth=Auth.Token(access_token))
    updated_count = 0

    for repo_full_name, pr_url in pending:
        try:
            repo = g.get_repo(repo_full_name)
            # Extract PR number from URL (e.g. .../pull/42)
            pr_number = _extract_pr_number(pr_url)
            if pr_number is None:
                continue

            pr = repo.get_pull(pr_number)
            if pr.state != "open":
                # PR was merged or closed — clear the pending_fix_url
                with get_session() as session:
                    clear_pending_fix_for_repo(session, repo_full_name=repo_full_name)
                    session.commit()
                updated_count += 1
        except GithubException:
            continue  # skip repos we can't access

    g.close()
    return updated_count


@activity.defn
async def sync_pr_status_activity(access_token: str) -> int:
    """Check all pending PRs on GitHub and clear those that are merged/closed."""
    return await asyncio.to_thread(_sync_pr_status, access_token)


# ---------------------------------------------------------------------------
# Phase 19: Portfolio & Profile Repos
# ---------------------------------------------------------------------------

def _fetch_repos_extended(access_token: str) -> list[dict]:
    """Fetch all owner repos with extended metadata (stars, fork, language, pushed_at)."""
    g = Github(auth=Auth.Token(access_token))
    repos: list[dict] = []
    for r in g.get_user().get_repos(affiliation="owner"):
        repos.append({
            "id": r.id,
            "name": r.name,
            "full_name": r.full_name,
            "description": r.description or "",
            "html_url": r.html_url,
            "private": r.private,
            "fork": r.fork,
            "stargazers_count": r.stargazers_count,
            "language": r.language,
            "pushed_at": r.pushed_at.isoformat() if r.pushed_at else None,
        })
    g.close()
    return repos


@activity.defn
async def fetch_repos_extended_activity(access_token: str) -> list[dict]:
    """Fetch all repos with extended metadata for portfolio selection."""
    return await asyncio.to_thread(_fetch_repos_extended, access_token)


def _create_or_update_profile_repo(
    username: str,
    readme_content: str,
    access_token: str,
) -> dict:
    """Create or update the username/username profile repo with a new README."""
    g = Github(access_token)
    user = g.get_user()
    profile_repo_name = username

    # Check if profile repo exists
    profile_repo = None
    try:
        profile_repo = g.get_repo(f"{username}/{profile_repo_name}")
    except GithubException as exc:
        if exc.status != 404:
            raise

    if profile_repo is None:
        # Create the special profile repo
        profile_repo = user.create_repo(
            name=profile_repo_name,
            description=f"{username}'s GitHub Profile",
            auto_init=True,
            private=False,
        )
        # Commit README directly to main since it's a new repo
        try:
            existing = profile_repo.get_contents("README.md", ref=profile_repo.default_branch)
            profile_repo.update_file(
                path="README.md",
                message="🌿 Gardener: Professional Profile README",
                content=readme_content,
                sha=existing.sha,
                branch=profile_repo.default_branch,
            )
        except GithubException:
            profile_repo.create_file(
                path="README.md",
                message="🌿 Gardener: Professional Profile README",
                content=readme_content,
                branch=profile_repo.default_branch,
            )
        g.close()
        return {
            "profile_url": profile_repo.html_url,
            "pr_url": None,
            "created_new": True,
        }

    # Profile repo exists — create a branch and PR
    target_branch = "gardener/update-profile"
    default_branch_name = profile_repo.default_branch
    default_branch = profile_repo.get_branch(default_branch_name)

    try:
        ref = profile_repo.get_git_ref(f"heads/{target_branch}")
        ref.edit(sha=default_branch.commit.sha, force=True)
    except GithubException:
        profile_repo.create_git_ref(
            ref=f"refs/heads/{target_branch}",
            sha=default_branch.commit.sha,
        )

    # Create or update README on the branch
    try:
        existing = profile_repo.get_contents("README.md", ref=target_branch)
        profile_repo.update_file(
            path="README.md",
            message="🌿 Gardener: Professional Profile README",
            content=readme_content,
            sha=existing.sha,
            branch=target_branch,
        )
    except GithubException:
        profile_repo.create_file(
            path="README.md",
            message="🌿 Gardener: Professional Profile README",
            content=readme_content,
            branch=target_branch,
        )

    # Check for existing PR
    existing_prs = profile_repo.get_pulls(
        state="open",
        head=f"{username}:{target_branch}",
        base=default_branch_name,
    )
    if existing_prs.totalCount > 0:
        pr = existing_prs[0]
        g.close()
        return {
            "profile_url": profile_repo.html_url,
            "pr_url": pr.html_url,
            "created_new": False,
        }

    # Create new PR
    try:
        pr = profile_repo.create_pull(
            title="🌿 Gardener: Professional Profile README",
            body=(
                "This profile README was auto-generated by the GitHub Gardener AI.\n\n"
                "It showcases your top projects, tech stack, and developer brand."
            ),
            head=target_branch,
            base=default_branch_name,
        )
        g.close()
        return {
            "profile_url": profile_repo.html_url,
            "pr_url": pr.html_url,
            "created_new": False,
        }
    except GithubException as e:
        if e.status == 422 and "No commits between" in str(e.data):
            g.close()
            return {
                "profile_url": profile_repo.html_url,
                "pr_url": f"{profile_repo.html_url}/tree/{target_branch}",
                "created_new": False,
            }
        raise


@activity.defn
async def create_or_update_profile_repo_activity(
    username: str,
    readme_content: str,
    access_token: str,
) -> dict:
    """Create or update the GitHub profile repo with a generated README."""
    return await asyncio.to_thread(
        _create_or_update_profile_repo, username, readme_content, access_token
    )
